language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAIZFKPTX6Q3ZZWZLA
  secret_access_key:
    secure: SOIW5cmYp8LdaqGrprhKvc/qsxzOLAt+fG+6qjy2mMWRCoEtDOwGHfHXMtO0R8kNdQNnvpxoETkiEO61ppbYtWX/cLGAQ2qEc89d1rXX+6dbCVzS2FiBW8ilG3qJ1QDwrfwIpG9bDeAGw93sma/h+PTeJF4KZTLlzce0VY10cvqTK/2BFW9rfp8FmM2AKsGqbZtQO5+pwrJaf6EIQA+meOj8589M/PXwt8W6hDnb1yFxeIkKDs30LLB/uniXvrwnnn4Mj3Z81jp6PQj0sU5/98d6fiZSOa+Uk/MP+CjS+5WLwJ+cymPm8ca0dOyz12ZPvFMiK5sbioaGAUAGj+7Fpd/BeTciO1vrBWk0OvmEvxoTR7+6YZmy6+upFViLvGWfqCf+gs9TXjz/M8ZhwyPGgpA86B5g4whSeiP4rMVF5giQPEY7X6rO1sQOjDmSaVXai0U7NhhWy+G3UQl4HWXLwYY+exW2bfxPq0J0s/dZZmoZ848uaVcdn82G9uuHudEstGtWqfd53RVz0kjbMTuv8+ycAu//D7hmWJDffKKa6yyBo4+yh3M8YzZOIepX6ZYK2HujM/ataKq8/Maf+qRJMljsnc/VRWXbJYXIVnANyY0nT3zRuoIKPQBqcG6hR/0Pj6g19a1C3jwh6mMrjaUH8phoqejB3tNJqwypr89SNaM=
  bucket: giver-web
  skip_cleanup: true
  region: ca-central-1
  local_dir: build
  on:
    branch: develop
notifications:
  email:
    recipients:
    - peter.yu@nexxspace.com
    on_success: never
    on_failure: always
