language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAJF6YDG7SFGGNTL7Q
  secret_access_key:
    secure: DJKZHYYmCW7425wCFDbF9W348tbaCE+cQrtAJa/WbKIXo5JDxnJKTi9upLXTD3dMdmVN1kuDtk/EsRQxVB3oTFZpU9CLAckH/cFcDYzvYxQWur4DuqLzvSzSVTfpwIooGKmgm5Z7eWnlB8bbYT4k8Kk1M96+wnTl679omq6VR2TdMfKH1HNKhAHTshUZoXGLl6Bm1mXuy+gV/kvH/ew7DWq5LCgTnqfdFQ7LVu8AZ7BDZxVu8lioAN1vkNrnqwmc/ORAcUCK1xKiZd5yR0GlRwNRXeghiHCQmJG/zBKONbRnfNiOTUE5Gh9uS7M65SYhGhBhKmZisGpXv225atIBrGSmfJmQG8gscX9rfxgtMPfFtEbPseVphTCi4djwIhfAxQYG0l9kxZVKVMz3oKcfOw0w3XHHY9AZhvNpaWGJjNvb7B6wrMsbEjlNgdIiYjsVeMH5v2ClP7wocPe24VvQ4iZUrRWGK7Oxn79Cp3D/EfXiYPjcMTZQmXrrBRTUzQtPB8elCRDWzZIRhbLptRJAdeDrrLtYgun8JuoFlkGJ+IrKto1KJLqJtclkNQ08Wc6vX5IpP7XWCZJQ/qlGS15ArmsWRsUjvD0wlDNtQ3Z7wWN1UZlIowYyOxkQLzydqiREVQuOOc0sU4pnkcyX1HySSzOW8T76z13yzq9dp9JcxJY=
  bucket: giver-web
  skip_cleanup: true
  region: ca-central-1
  local-dir: build
  on:
    repo: I-Donate-This/giver-react-web
    branch: develop
notifications:
  email:
    recipients:
    - peter.yu@nexxspace.com
    on_success: never
    on_failure: always
