language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAIZFKPTX6Q3ZZWZLA
  secret_access_key:
    secure: hx6MIsHXP3vurMy4HBPZdXnv8Wcrz+7BMdRy+MsxbAum/0wYemmpHiF395tEclzyXrCAhQqLBbomWTFJi7h4lCELpGbzU2VRqCpQCT7KaI+vGiqsL+AnSTR9xzIGBNeAgAmGkLMPWnldrBeKz/Nz2GLU5K8UNbUotekkWwkflGU+GSAaroZCCbBDPrdwIIVBQZ40ikjEhF3YaT6/3PDjIZD66GCmsCxJwb043D7ni8mKjedm+Ua39qIj7x9D+MeEbkr19x86nnCkhDYImFuWYApB1DmRe4Mu8vDONL8HIod4y6leUljVlH2tHQqAWM+LikPTyFmSgnHEysy8vApGpu5dUnVdPFNhPIw9Jw5Yn3gaHtiRMd0le2TKXMC7cUfR+KlNOEM+F+t9bnXP2rlH9MBDC1MvPS+2HGbndsS3H76yw1p5/51BJfSHqPJHcRrN3r8RghQxp3rSQxPKW8Dl+N3I1V+mpxZYKorf6LPCsXOCrs9unasY0M979Q3lBVqxAdyUHhCBxcv/RYUVEMyvpYXfUKrbgbaOHzBpPSskEeMDFOe/bZs1TUAgNoYfGWVRMTTKhGiFVn6ABCh7bwxfImKo1JL6xbjg0RQpD/N9CUQ7kT1NS2rRn2we4ZuqGFTIFbAKhfTHU37LK6EtT6QF4D3HDsQy+9jnSo1QoHLAhqU=
  bucket: giver-web
  skip_cleanup: true
  region: ca-central-1
  local_dir: build
  on:
    branch: develop
notifications:
  email:
    recipients:
    - peter.yu@nexxspace.com
    on_success: never
    on_failure: always
