language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
before_deploy:
  - rvm 1.9.3 do gem install aws-sdk -v 2.1.36
deploy:
  provider: s3
  access_key_id: "AKIAIKEN3CT355R4X55A"
  secret_access_key:
    secure: "ZMKxNIRz0ydQH6/xugMQnv6QVn2gJZX7nhEhs/8HnFd5vA4Em2hwEQIbye82RPCv7qiseNQKaFH+Fu/Waq5y71PbZxzUVXe23Hs/tJosbrYZVOxiox2rLimcecSQ49zN78L+IQf1UBxc+/QnMnMoTeuhb/fI8G1q5AbLJBKIfFttU7GIvJ1Hd3gAEpggzbcJAk7db4zDgLwd+S3BFwbyu461FJI2clYYmk0PG1aoKuhZjaldKXiaxOC4qufFTwtthW6/iq6+U4P/3IGUMnAcgkB4sX+1CYZ1glLDiUqIoulBXWxDSx7BfGTusPwflaRAcS3Z29f/gs+CDjCc1WGy4gZ+9q2LMIC6tpZy8pEpUEgLS6w49eBFtrD6exQoS+jl8GJsaFnXt+w/gt0oVQAdEYfya5lKqzQ7sUe7ZDYZfP3Cyrm6vflkbIaB2RkXlW5P+iZ5PngQh86PPsnlBqlWxa0EP+QCWAW6nGFfHBmU3ez6CjcMO4gdE3C/1UbmrjugSOhXdms3CeG6InRhcOjgdKYN5MxM3ECQjnmdZqlCvDDA38aEy750I/NKYnHHtFQuqQKBfdfxciwh2CQwbnmijO8eL9hT0cJaWb15yDsTcu2C4AiN4MDTv+cLQdpjxMQuQKZLO8jFezDFC1XxNzzoiTLvdUi4nwNATh6YfVP1S6k="
  bucket: giver-web
  skip_cleanup: true
  region: ca-central-1
  local-dir: build
  on:
    repo: I-Donate-This/giver-react-web
    branch: develop
notifications:
  email:
    recipients:
    - peter.yu@nexxspace.com
    on_success: never
    on_failure: always
